// Integration: real Builder output (cross-repo compatibility).
//
// These fixtures were generated by the actual Agent Plugin Builder
// (https://github.com/HiAi-gg/agent-plugin-builder, commit 7a0b9bd8) and
// copied byte-for-byte into tests/fixtures/builder-generated/real-builder/.
// Doctor must validate every command Builder ships (`init`, `create`, and
// `migrate --from claude|cursor`) with zero error/critical diagnostics.

import { describe, expect, test } from 'bun:test';
import { computeExitCode } from '@agent-plugins-doctor/cli';
import { loadPlugin } from '@agent-plugins-doctor/parser';
import { validatePlugin } from '@agent-plugins-doctor/rules';
import { fixturePath } from './helpers.js';

// Every real Builder command's output must validate cleanly (exit 0).
const REAL_BUILDER_FIXTURES = [
  'builder-generated/real-builder/init',
  'builder-generated/real-builder/create-skills',
  'builder-generated/real-builder/create-mcp',
  'builder-generated/real-builder/migrate-claude',
  'builder-generated/real-builder/migrate-cursor',
];

describe('real Builder output', () => {
  test('init output passes validation', async () => {
    const { plugin, parseDiagnostics } = await loadPlugin(
      fixturePath('builder-generated/real-builder/init'),
    );
    const result = await validatePlugin(plugin);
    const diagnostics = [...parseDiagnostics, ...result.diagnostics];
    expect(
      diagnostics.filter((d) => d.severity === 'error'),
      `error diagnostics: ${JSON.stringify(
        diagnostics.filter((d) => d.severity === 'error'),
      )}`,
    ).toHaveLength(0);
    expect(diagnostics.filter((d) => d.severity === 'critical')).toHaveLength(
      0,
    );
    expect(computeExitCode(diagnostics)).toBe(0);
  });

  test('create-skills output passes validation', async () => {
    const { plugin, parseDiagnostics } = await loadPlugin(
      fixturePath('builder-generated/real-builder/create-skills'),
    );
    const result = await validatePlugin(plugin);
    const diagnostics = [...parseDiagnostics, ...result.diagnostics];
    expect(diagnostics.filter((d) => d.severity === 'error')).toHaveLength(0);
    expect(diagnostics.filter((d) => d.severity === 'critical')).toHaveLength(
      0,
    );
    expect(computeExitCode(diagnostics)).toBe(0);
  });

  test('create-mcp output passes validation', async () => {
    const { plugin, parseDiagnostics } = await loadPlugin(
      fixturePath('builder-generated/real-builder/create-mcp'),
    );
    const result = await validatePlugin(plugin);
    const diagnostics = [...parseDiagnostics, ...result.diagnostics];
    expect(diagnostics.filter((d) => d.severity === 'error')).toHaveLength(0);
    expect(diagnostics.filter((d) => d.severity === 'critical')).toHaveLength(
      0,
    );
    expect(computeExitCode(diagnostics)).toBe(0);
  });

  test('all real Builder fixtures validate with zero error/critical diagnostics', async () => {
    for (const fixture of REAL_BUILDER_FIXTURES) {
      const { plugin, parseDiagnostics } = await loadPlugin(
        fixturePath(fixture),
      );
      const result = await validatePlugin(plugin);
      const diagnostics = [...parseDiagnostics, ...result.diagnostics];
      expect(
        diagnostics.filter((d) => d.severity === 'error'),
        `${fixture}: unexpected error diagnostics: ${JSON.stringify(
          diagnostics.filter((d) => d.severity === 'error'),
        )}`,
      ).toHaveLength(0);
      expect(
        diagnostics.filter((d) => d.severity === 'critical'),
        `${fixture}: unexpected critical diagnostics`,
      ).toHaveLength(0);
      expect(computeExitCode(diagnostics), `${fixture}: exit code`).toBe(0);
    }
  });
});
